title: j3dus0r's Writeups
description: CTF Challenges & Machine Writeups
author: wall4cee
email: pro.reset222@passfwd.com

# Theme
theme: jekyll-theme-hacker

# URL
url: "https://wall4cee.github.io"
baseurl: "/writeups"

# Social
github_username: wall4cee

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
